import fs from "fs";
import path from "path";

// Minimal env docs generator: scans src/lib/shared/env or similar for getEnv usage
async function main() {
  const root = process.cwd();
  const outDir = path.join(root, "docs", "reference");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  // Minimal placeholder content
  const md = `# Environment Reference\n\nThis file is autogenerated: list of env vars should be generated from the repo's env schema (getEnv).\n\n- NODE_ENV: development|production\n- NEXT_PUBLIC_SENTRY_DSN: optional\n`;

  fs.writeFileSync(path.join(outDir, "env.md"), md);
  console.log("Wrote docs/reference/env.md");
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});



