
import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const projectRoot = process.cwd();
const stylesDir = join(projectRoot, 'styles', 'ui');
const variantsFile = join(projectRoot, 'styles', 'ui', 'shared', 'component-variants.ts');

// ⛔ Explicit skip-list to prevent reintroducing removed aggregators
const SKIP_PATHS = new Set<string>([
  'styles/ui/shared/component-variants.ts',
  'styles/ui/shared/index.ts',
]);

const ATOMIC_LEVELS = ['atoms', 'molecules', 'organisms'];

async function generateVariantsIndex() {
  let content = `// styles/ui/shared/component-variants.ts
// Consolidated variants export - Re-exports all individual variant files
// This file provides a single import point for all component variants
//
// ⚠️ THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
//    Run \`pnpm gen:variants\` to regenerate.
`;

  // If this output is explicitly skipped, do nothing (no-op)
  const relOutput = 'styles/ui/shared/component-variants.ts';
  if (SKIP_PATHS.has(relOutput)) {
    console.log('⏭️  Skipping generation of styles/ui/shared/component-variants.ts (guarded)');
    return;
  }

  for (const level of ATOMIC_LEVELS) {
    content += `\n// ============================================================================
// ${level.toUpperCase()} - ${getCategoryDescription(level)}
// ============================================================================
\n`;
    const levelDir = join(stylesDir, level);
    const files = await readdir(levelDir);
    const tsFiles = files.filter(f => f.endsWith('.ts') && f !== 'index.ts');

    for (const file of tsFiles) {
      const moduleName = file.replace('.ts', '');
      content += `export * from '../${level}/${moduleName}';\n`;
    }
  }
  
  content += `\n// Note: This consolidated file is auto-generated from the individual
// variant files to avoid manual maintenance. 
`;

  await writeFile(variantsFile, content, 'utf-8');
  console.log('✅ Successfully generated styles/ui/shared/component-variants.ts');
}

function getCategoryDescription(level: string): string {
  switch (level) {
    case 'atoms':
      return 'Basic building blocks';
    case 'molecules':
      return 'Component combinations';
    case 'organisms':
      return 'Complex component compositions';
    default:
      return 'Component variants';
  }
}

generateVariantsIndex().catch(err => {
  console.error('❌ Error generating styles/ui/shared/component-variants.ts:', err);
  process.exit(1);
}); 

