// Shared env mock creator for script validation tests
export function createMockEnv(overrides: Partial<any> = {}) {
  return {
    NODE_ENV: 'development' as const,
    CSP_SCRIPT_DOMAINS: [],
    CSP_STYLE_DOMAINS: [],
    CSP_FONT_DOMAINS: [],
    CSP_IMG_DOMAINS: [],
    CSP_CONNECT_DOMAINS: [],
    CSP_FRAME_DOMAINS: [],
    CSP_REPORT_URI: undefined,
    CSP_REPORT_ONLY: false,
    AUTH_IDLE_TIMEOUT_MIN: 30,
    NEXT_TELEMETRY_DISABLED: false,
    NEXT_PUBLIC_APP_URL: undefined,
    NEXT_PUBLIC_STAGE: undefined,
    OPENAI_TOKENS_WARN_THRESHOLD: undefined,
    TURNSTILE_SECRET_KEY: undefined,
    OPENAI_SQL_MODEL: undefined,
    OPENAI_CHART_MODEL: undefined,
    // Intercom removed for MVP
    OPENAI_RATE_LIMIT_PER_MIN: undefined,
    OPENAI_TIMEOUT: undefined,
    OPENAI_MAX_RETRIES: undefined,
    OPENAI_SLOW_THRESHOLD_MS: undefined,
    CLICKHOUSE_RATE_LIMIT_PER_MIN: undefined,
    CLICKHOUSE_SLOW_QUERY_MS: undefined,
    // External SSO (removed)
    CORS_ORIGINS: undefined,
    OPENAI_ORG_ID: undefined,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: undefined,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: undefined,
    NEXT_PUBLIC_APP_NAME: undefined,
    NEXT_PUBLIC_APP_VERSION: undefined,
    NEXT_PUBLIC_API_URL: undefined,
    npm_package_version: undefined,
    NEXT_PUBLIC_SITE_URL: undefined,
    SENTRY_ORG: undefined,
    SENTRY_PROJECT: undefined,
    PG_STAT_TOP_N: undefined,
    VERCEL_ENV: undefined,
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: undefined,
    CLERK_SECRET_KEY: undefined,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: undefined,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: undefined,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: undefined,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: undefined,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: undefined,
    CLERK_WEBHOOK_SECRET: undefined,
    NEXT_PUBLIC_PLACEHOLDER_IMAGE_BASE: undefined,
    OPENAI_API_KEY: undefined,
    CLICKHOUSE_URL: undefined,
    CLICKHOUSE_PASSWORD: undefined,
    CLICKHOUSE_DATABASE: undefined,
    CLICKHOUSE_READONLY_USER: undefined,
    SUPABASE_URL: undefined,
    SUPABASE_SERVICE_ROLE_KEY: undefined,
    NEXT_PUBLIC_SUPABASE_URL: undefined,
    STRIPE_SECRET_KEY: undefined,
    SENTRY_DSN: undefined,
    NEXT_PUBLIC_SENTRY_DSN: undefined,
    UPSTASH_REDIS_REST_URL: undefined,
    UPSTASH_REDIS_REST_TOKEN: undefined,
    ...overrides,
  };
}



