// Generated by scripts/manage-docs.ts. Do not edit.
export const docs = [
  {
    "path": ".cursor/rules/readme.md",
    "title": "Rules"
  },
  {
    "path": ".github/readme.md",
    "title": ".github"
  },
  {
    "path": ".github/scripts/readme.md",
    "title": "Scripts"
  },
  {
    "path": ".husky/readme.md",
    "title": ".husky"
  },
  {
    "path": ".vscode/readme.md",
    "title": ".vscode"
  },
  {
    "path": "actions/readme.md",
    "title": "Actions"
  },
  {
    "path": "api/readme.md",
    "title": "API — OpenAPI Specs & Tooling"
  },
  {
    "path": "app/(auth)/readme.md",
    "title": "(auth)"
  },
  {
    "path": "app/(marketing)/readme.md",
    "title": "(marketing)"
  },
  {
    "path": "app/(protected)/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "app/(protected)/readme.md",
    "title": "(protected)"
  },
  {
    "path": "app/api/health/readme.md",
    "title": "Health"
  },
  {
    "path": "app/api/internal/readme.md",
    "title": "Internal"
  },
  {
    "path": "app/api/readme.md",
    "title": "Api"
  },
  {
    "path": "app/api/v1/readme.md",
    "title": "V1"
  },
  {
    "path": "app/readme.md",
    "title": "App"
  },
  {
    "path": "components/auth/readme.md",
    "title": "components/auth"
  },
  {
    "path": "components/billing/readme.md",
    "title": "components/billing"
  },
  {
    "path": "components/dashboard/entity/addresses/readme.md",
    "title": "components/dashboard/entity/addresses"
  },
  {
    "path": "components/dashboard/entity/companies/readme.md",
    "title": "components/dashboard/entity/companies"
  },
  {
    "path": "components/dashboard/entity/projects/readme.md",
    "title": "components/dashboard/entity/projects"
  },
  {
    "path": "components/dashboard/entity/readme.md",
    "title": "components/dashboard/entity"
  },
  {
    "path": "components/dashboard/entity/shared/readme.md",
    "title": "components/dashboard/entity/shared"
  },
  {
    "path": "components/dashboard/entity/shared/renderers/readme.md",
    "title": "components/dashboard/entity/shared/renderers"
  },
  {
    "path": "components/dashboard/layout/readme.md",
    "title": "components/dashboard/layout"
  },
  {
    "path": "components/dashboard/readme.md",
    "title": "components/dashboard"
  },
  {
    "path": "components/dashboard/sidebar/readme.md",
    "title": "components/dashboard/sidebar"
  },
  {
    "path": "components/forms/readme.md",
    "title": "components/forms"
  },
  {
    "path": "components/insights/layout/readme.md",
    "title": "components/insights/layout"
  },
  {
    "path": "components/insights/readme.md",
    "title": "components/insights"
  },
  {
    "path": "components/landing/layout/readme.md",
    "title": "components/landing/layout"
  },
  {
    "path": "components/landing/readme.md",
    "title": "components/landing"
  },
  {
    "path": "components/landing/sections/market-insights/readme.md",
    "title": "components/landing/sections/market-insights"
  },
  {
    "path": "components/landing/sections/readme.md",
    "title": "components/landing/sections"
  },
  {
    "path": "components/landing/sections/roi/readme.md",
    "title": "components/landing/sections/roi"
  },
  {
    "path": "components/landing/widgets/readme.md",
    "title": "components/landing/widgets"
  },
  {
    "path": "components/marketing/readme.md",
    "title": "components/marketing"
  },
  {
    "path": "components/marketing/sections/contact/readme.md",
    "title": "components/marketing/sections/contact"
  },
  {
    "path": "components/marketing/sections/legal/readme.md",
    "title": "components/marketing/sections/legal"
  },
  {
    "path": "components/marketing/sections/pricing/readme.md",
    "title": "components/marketing/sections/pricing"
  },
  {
    "path": "components/marketing/sections/readme.md",
    "title": "components/marketing/sections"
  },
  {
    "path": "components/marketing/widgets/readme.md",
    "title": "components/marketing/widgets"
  },
  {
    "path": "components/readme.md",
    "title": "components"
  },
  {
    "path": "components/ui/atoms/icon/readme.md",
    "title": "components/ui/atoms/icon"
  },
  {
    "path": "components/ui/atoms/progress/readme.md",
    "title": "components/ui/atoms/progress"
  },
  {
    "path": "components/ui/atoms/readme.md",
    "title": "components/ui/atoms"
  },
  {
    "path": "components/ui/molecules/readme.md",
    "title": "components/ui/molecules"
  },
  {
    "path": "components/ui/molecules/shared/readme.md",
    "title": "components/ui/molecules/shared"
  },
  {
    "path": "components/ui/molecules/tab-switcher/readme.md",
    "title": "components/ui/molecules/tab-switcher"
  },
  {
    "path": "components/ui/organisms/footer-system/readme.md",
    "title": "components/ui/organisms/footer-system"
  },
  {
    "path": "components/ui/organisms/navbar/readme.md",
    "title": "components/ui/organisms/navbar"
  },
  {
    "path": "components/ui/organisms/readme.md",
    "title": "components/ui/organisms"
  },
  {
    "path": "components/ui/patterns/readme.md",
    "title": "components/ui/patterns"
  },
  {
    "path": "components/ui/readme.md",
    "title": "components/ui"
  },
  {
    "path": "components/ui/shared/readme.md",
    "title": "components/ui/shared"
  },
  {
    "path": "config/readme.md",
    "title": "Config"
  },
  {
    "path": "config/typescript/readme.md",
    "title": "Typescript"
  },
  {
    "path": "contexts/readme.md",
    "title": "contexts"
  },
  {
    "path": "db/readme.md",
    "title": "Database Assets"
  },
  {
    "path": "docs/readme.md",
    "title": "docs"
  },
  {
    "path": "docs/security/readme.md",
    "title": "docs/security"
  },
  {
    "path": "eslint-plugin-corso/readme.md",
    "title": "Eslint Plugin Corso"
  },
  {
    "path": "hooks/chat/readme.md",
    "title": "hooks/chat"
  },
  {
    "path": "hooks/dashboard/readme.md",
    "title": "hooks/dashboard"
  },
  {
    "path": "hooks/integrations/readme.md",
    "title": "hooks/integrations"
  },
  {
    "path": "hooks/marketing/readme.md",
    "title": "hooks/marketing"
  },
  {
    "path": "hooks/readme.md",
    "title": "hooks"
  },
  {
    "path": "hooks/security/readme.md",
    "title": "hooks/security"
  },
  {
    "path": "lib/actions/readme.md",
    "title": "lib/actions"
  },
  {
    "path": "lib/api/readme.md",
    "title": "lib/api"
  },
  {
    "path": "lib/auth/readme.md",
    "title": "lib/auth"
  },
  {
    "path": "lib/chat/readme.md",
    "title": "lib/chat"
  },
  {
    "path": "lib/core/readme.md",
    "title": "lib/core"
  },
  {
    "path": "lib/dashboard/readme.md",
    "title": "lib/dashboard"
  },
  {
    "path": "lib/integrations/readme.md",
    "title": "lib/integrations"
  },
  {
    "path": "lib/marketing/readme.md",
    "title": "lib/marketing"
  },
  {
    "path": "lib/middleware/readme.md",
    "title": "lib/middleware"
  },
  {
    "path": "lib/monitoring/readme.md",
    "title": "lib/monitoring"
  },
  {
    "path": "lib/ratelimiting/readme.md",
    "title": "lib/ratelimiting"
  },
  {
    "path": "lib/readme.md",
    "title": "lib"
  },
  {
    "path": "lib/security/readme.md",
    "title": "lib/security"
  },
  {
    "path": "lib/server/readme.md",
    "title": "lib/server"
  },
  {
    "path": "lib/services/entity/readme.md",
    "title": "lib/services/entity"
  },
  {
    "path": "lib/shared/readme.md",
    "title": "lib/shared"
  },
  {
    "path": "lib/shared/utils/readme.md",
    "title": "lib/shared/utils"
  },
  {
    "path": "lib/shared/validation/readme.md",
    "title": "lib/shared/validation"
  },
  {
    "path": "lib/validators/readme.md",
    "title": "lib/validators"
  },
  {
    "path": "public/readme.md",
    "title": "Public"
  },
  {
    "path": "readme.md",
    "title": "."
  },
  {
    "path": "scripts/analysis/readme.md",
    "title": "scripts/analysis"
  },
  {
    "path": "scripts/audit/readme.md",
    "title": "scripts/audit"
  },
  {
    "path": "scripts/ci/readme.md",
    "title": "scripts/ci"
  },
  {
    "path": "scripts/codemods/readme.md",
    "title": "scripts/codemods"
  },
  {
    "path": "scripts/docs/readme.md",
    "title": "scripts/docs"
  },
  {
    "path": "scripts/lint/readme.md",
    "title": "scripts/lint"
  },
  {
    "path": "scripts/maintenance/readme.md",
    "title": "scripts/maintenance"
  },
  {
    "path": "scripts/readme.md",
    "title": "scripts"
  },
  {
    "path": "scripts/rules/ast-grep/readme.md",
    "title": "scripts/rules/ast-grep"
  },
  {
    "path": "scripts/rules/readme.md",
    "title": "scripts/rules"
  },
  {
    "path": "scripts/setup/readme.md",
    "title": "scripts/setup"
  },
  {
    "path": "scripts/test/readme.md",
    "title": "scripts/test"
  },
  {
    "path": "scripts/utils/readme.md",
    "title": "scripts/utils"
  },
  {
    "path": "scripts/validation/readme.md",
    "title": "scripts/validation"
  },
  {
    "path": "styles/readme.md",
    "title": "styles"
  },
  {
    "path": "styles/tokens/readme.md",
    "title": "styles/tokens"
  },
  {
    "path": "styles/ui/atoms/readme.md",
    "title": "styles/ui/atoms"
  },
  {
    "path": "styles/ui/molecules/readme.md",
    "title": "styles/ui/molecules"
  },
  {
    "path": "styles/ui/organisms/readme.md",
    "title": "styles/ui/organisms"
  },
  {
    "path": "styles/ui/readme.md",
    "title": "styles/ui"
  },
  {
    "path": "styles/ui/shared/readme.md",
    "title": "styles/ui/shared"
  },
  {
    "path": "supabase/readme.md",
    "title": "Supabase"
  },
  {
    "path": "tests/api/readme.md",
    "title": "Api"
  },
  {
    "path": "tests/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "tests/readme.md",
    "title": "Tests"
  },
  {
    "path": "tests/runtime-boundary/readme.md",
    "title": "Runtime Boundary"
  },
  {
    "path": "tests/security/readme.md",
    "title": "Security"
  },
  {
    "path": "tests/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "tests/support/harness/readme.md",
    "title": "Harness"
  },
  {
    "path": "tests/support/readme.md",
    "title": "Support"
  },
  {
    "path": "tests/support/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "types/api/readme.md",
    "title": "types/api"
  },
  {
    "path": "types/auth/readme.md",
    "title": "types/auth"
  },
  {
    "path": "types/chat/readme.md",
    "title": "types/chat"
  },
  {
    "path": "types/config/readme.md",
    "title": "types/config"
  },
  {
    "path": "types/dashboard/readme.md",
    "title": "types/dashboard"
  },
  {
    "path": "types/forms/readme.md",
    "title": "types/forms"
  },
  {
    "path": "types/integrations/readme.md",
    "title": "types/integrations"
  },
  {
    "path": "types/integrations/supabase/readme.md",
    "title": "types/integrations/supabase"
  },
  {
    "path": "types/marketing/readme.md",
    "title": "types/marketing"
  },
  {
    "path": "types/readme.md",
    "title": "types"
  },
  {
    "path": "types/security/readme.md",
    "title": "types/security"
  },
  {
    "path": "types/shared/config/readme.md",
    "title": "types/shared/config"
  },
  {
    "path": "types/shared/core/readme.md",
    "title": "types/shared/core"
  },
  {
    "path": "types/shared/data/readme.md",
    "title": "types/shared/data"
  },
  {
    "path": "types/shared/performance/readme.md",
    "title": "types/shared/performance"
  },
  {
    "path": "types/shared/readme.md",
    "title": "types/shared"
  },
  {
    "path": "types/shared/system/readme.md",
    "title": "types/shared/system"
  },
  {
    "path": "types/shared/utils/readme.md",
    "title": "types/shared/utils"
  },
  {
    "path": "types/validators/readme.md",
    "title": "types/validators"
  },
  {
    "path": "docs/security/dependency-policy.md",
    "title": "Dependency Policy"
  }
] as const;
