// Generated by scripts/manage-docs.ts. Do not edit.
export const docs = [
  {
    "path": ".cursor/commands/readme.md",
    "title": "Commands"
  },
  {
    "path": ".cursor/rules/readme.md",
    "title": "Rules"
  },
  {
    "path": ".github/readme.md",
    "title": ".github"
  },
  {
    "path": ".github/scripts/readme.md",
    "title": "Scripts"
  },
  {
    "path": ".husky/readme.md",
    "title": ".husky"
  },
  {
    "path": ".vscode/readme.md",
    "title": ".vscode"
  },
  {
    "path": "api/readme.md",
    "title": "API — OpenAPI Specs & Tooling"
  },
  {
    "path": "app/(auth)/readme.md",
    "title": "(auth)"
  },
  {
    "path": "app/(marketing)/readme.md",
    "title": "(marketing)"
  },
  {
    "path": "app/(protected)/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "app/(protected)/readme.md",
    "title": "(protected)"
  },
  {
    "path": "app/api/health/readme.md",
    "title": "Health"
  },
  {
    "path": "app/api/internal/readme.md",
    "title": "Internal"
  },
  {
    "path": "app/api/readme.md",
    "title": "Api"
  },
  {
    "path": "app/api/v1/readme.md",
    "title": "V1"
  },
  {
    "path": "app/readme.md",
    "title": "App"
  },
  {
    "path": "components/auth/readme.md",
    "title": "Auth"
  },
  {
    "path": "components/billing/readme.md",
    "title": "Billing"
  },
  {
    "path": "components/chat/readme.md",
    "title": "Chat"
  },
  {
    "path": "components/dashboard/entities/addresses/readme.md",
    "title": "Addresses"
  },
  {
    "path": "components/dashboard/entities/companies/readme.md",
    "title": "Companies"
  },
  {
    "path": "components/dashboard/entities/projects/readme.md",
    "title": "Projects"
  },
  {
    "path": "components/dashboard/entities/readme.md",
    "title": "Entities"
  },
  {
    "path": "components/dashboard/layout/readme.md",
    "title": "Layout"
  },
  {
    "path": "components/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "components/dashboard/sidebar/readme.md",
    "title": "Sidebar"
  },
  {
    "path": "components/forms/readme.md",
    "title": "Forms"
  },
  {
    "path": "components/insights/layout/readme.md",
    "title": "Layout"
  },
  {
    "path": "components/insights/readme.md",
    "title": "Insights"
  },
  {
    "path": "components/landing/layout/readme.md",
    "title": "Layout"
  },
  {
    "path": "components/landing/readme.md",
    "title": "Landing"
  },
  {
    "path": "components/landing/sections/market-insights/readme.md",
    "title": "Market Insights"
  },
  {
    "path": "components/landing/sections/product-showcase/readme.md",
    "title": "Product Showcase"
  },
  {
    "path": "components/landing/sections/readme.md",
    "title": "Sections"
  },
  {
    "path": "components/landing/sections/roi/readme.md",
    "title": "Roi"
  },
  {
    "path": "components/landing/widgets/readme.md",
    "title": "Widgets"
  },
  {
    "path": "components/marketing/readme.md",
    "title": "Marketing"
  },
  {
    "path": "components/marketing/sections/contact/readme.md",
    "title": "Contact"
  },
  {
    "path": "components/marketing/sections/legal/readme.md",
    "title": "Legal"
  },
  {
    "path": "components/marketing/sections/pricing/readme.md",
    "title": "Pricing"
  },
  {
    "path": "components/marketing/sections/readme.md",
    "title": "Sections"
  },
  {
    "path": "components/marketing/widgets/readme.md",
    "title": "Widgets"
  },
  {
    "path": "components/readme.md",
    "title": "Components"
  },
  {
    "path": "components/ui/atoms/icon/readme.md",
    "title": "Icon"
  },
  {
    "path": "components/ui/atoms/readme.md",
    "title": "Atoms"
  },
  {
    "path": "components/ui/molecules/readme.md",
    "title": "Molecules"
  },
  {
    "path": "components/ui/organisms/footer-system/readme.md",
    "title": "Footer System"
  },
  {
    "path": "components/ui/organisms/navbar/readme.md",
    "title": "Navbar"
  },
  {
    "path": "components/ui/organisms/readme.md",
    "title": "Organisms"
  },
  {
    "path": "components/ui/patterns/readme.md",
    "title": "Patterns"
  },
  {
    "path": "components/ui/readme.md",
    "title": "Ui"
  },
  {
    "path": "components/ui/shared/readme.md",
    "title": "Shared"
  },
  {
    "path": "config/readme.md",
    "title": "Config"
  },
  {
    "path": "config/typescript/readme.md",
    "title": "Typescript"
  },
  {
    "path": "docs/decisions/readme.md",
    "title": "Decisions"
  },
  {
    "path": "docs/feature-notes/readme.md",
    "title": "Feature Notes"
  },
  {
    "path": "docs/qa/readme.md",
    "title": "Qa"
  },
  {
    "path": "docs/readme.md",
    "title": "Docs"
  },
  {
    "path": "docs/references/readme.md",
    "title": "References"
  },
  {
    "path": "docs/security/readme.md",
    "title": "Security"
  },
  {
    "path": "eslint-plugin-corso/readme.md",
    "title": "Eslint Plugin Corso"
  },
  {
    "path": "lib/actions/readme.md",
    "title": "Actions"
  },
  {
    "path": "lib/api/readme.md",
    "title": "Api"
  },
  {
    "path": "lib/auth/readme.md",
    "title": "Auth"
  },
  {
    "path": "lib/chat/readme.md",
    "title": "Chat"
  },
  {
    "path": "lib/core/readme.md",
    "title": "Core"
  },
  {
    "path": "lib/entities/readme.md",
    "title": "Entities"
  },
  {
    "path": "lib/integrations/readme.md",
    "title": "Integrations"
  },
  {
    "path": "lib/marketing/readme.md",
    "title": "Marketing"
  },
  {
    "path": "lib/middleware/readme.md",
    "title": "Middleware"
  },
  {
    "path": "lib/monitoring/readme.md",
    "title": "Monitoring"
  },
  {
    "path": "lib/ratelimiting/readme.md",
    "title": "Ratelimiting"
  },
  {
    "path": "lib/readme.md",
    "title": "Lib"
  },
  {
    "path": "lib/security/readme.md",
    "title": "Security"
  },
  {
    "path": "lib/server/readme.md",
    "title": "Server"
  },
  {
    "path": "lib/shared/readme.md",
    "title": "Shared"
  },
  {
    "path": "lib/validators/readme.md",
    "title": "Validators"
  },
  {
    "path": "public/readme.md",
    "title": "Public"
  },
  {
    "path": "readme.md",
    "title": "README.md"
  },
  {
    "path": "scripts/analysis/readme.md",
    "title": "Analysis"
  },
  {
    "path": "scripts/audit/readme.md",
    "title": "Audit"
  },
  {
    "path": "scripts/codemods/readme.md",
    "title": "Codemods"
  },
  {
    "path": "scripts/docs/readme.md",
    "title": "Docs"
  },
  {
    "path": "scripts/lint/readme.md",
    "title": "Lint"
  },
  {
    "path": "scripts/maintenance/docs/readme.md",
    "title": "Docs"
  },
  {
    "path": "scripts/maintenance/readme.md",
    "title": "Maintenance"
  },
  {
    "path": "scripts/readme.md",
    "title": "Scripts"
  },
  {
    "path": "scripts/rules/ast-grep/readme.md",
    "title": "Ast Grep"
  },
  {
    "path": "scripts/rules/readme.md",
    "title": "Rules"
  },
  {
    "path": "scripts/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "scripts/tools/readme.md",
    "title": "Tools"
  },
  {
    "path": "scripts/utils/readme.md",
    "title": "Utils"
  },
  {
    "path": "scripts/validation/readme.md",
    "title": "Validation"
  },
  {
    "path": "styles/readme.md",
    "title": "Styles"
  },
  {
    "path": "styles/tokens/readme.md",
    "title": "Tokens"
  },
  {
    "path": "styles/ui/atoms/readme.md",
    "title": "Atoms"
  },
  {
    "path": "styles/ui/molecules/readme.md",
    "title": "Molecules"
  },
  {
    "path": "styles/ui/organisms/readme.md",
    "title": "Organisms"
  },
  {
    "path": "styles/ui/patterns/readme.md",
    "title": "Patterns"
  },
  {
    "path": "styles/ui/readme.md",
    "title": "Ui"
  },
  {
    "path": "styles/ui/shared/readme.md",
    "title": "Shared"
  },
  {
    "path": "supabase/readme.md",
    "title": "Supabase"
  },
  {
    "path": "tests/api/readme.md",
    "title": "Api"
  },
  {
    "path": "tests/auth/readme.md",
    "title": "Auth"
  },
  {
    "path": "tests/chat/readme.md",
    "title": "Chat"
  },
  {
    "path": "tests/core/readme.md",
    "title": "Core"
  },
  {
    "path": "tests/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "tests/e2e/readme.md",
    "title": "E2e"
  },
  {
    "path": "tests/insights/readme.md",
    "title": "Insights"
  },
  {
    "path": "tests/integrations/readme.md",
    "title": "Integrations"
  },
  {
    "path": "tests/lib/readme.md",
    "title": "Lib"
  },
  {
    "path": "tests/readme.md",
    "title": "Tests"
  },
  {
    "path": "tests/routes/readme.md",
    "title": "Routes"
  },
  {
    "path": "tests/runtime-boundary/readme.md",
    "title": "Runtime Boundary"
  },
  {
    "path": "tests/scripts/readme.md",
    "title": "Scripts"
  },
  {
    "path": "tests/security/readme.md",
    "title": "Security"
  },
  {
    "path": "tests/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "tests/styles/readme.md",
    "title": "Styles"
  },
  {
    "path": "tests/support/harness/readme.md",
    "title": "Harness"
  },
  {
    "path": "tests/support/readme.md",
    "title": "Support"
  },
  {
    "path": "tests/support/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "tests/types/readme.md",
    "title": "Types"
  },
  {
    "path": "tests/ui/readme.md",
    "title": "Ui"
  },
  {
    "path": "tests/vendors/readme.md",
    "title": "Vendors"
  },
  {
    "path": "types/api/readme.md",
    "title": "Api"
  },
  {
    "path": "types/chat/readme.md",
    "title": "Chat"
  },
  {
    "path": "types/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "types/forms/readme.md",
    "title": "Forms"
  },
  {
    "path": "types/marketing/readme.md",
    "title": "Marketing"
  },
  {
    "path": "types/readme.md",
    "title": "Types"
  },
  {
    "path": "types/shared/readme.md",
    "title": "Shared"
  },
  {
    "path": "types/supabase/readme.md",
    "title": "Supabase"
  },
  {
    "path": "docs/security/dependency-policy.md",
    "title": "Dependency Policy"
  }
] as const;
