// Generated by scripts/manage-docs.ts. Do not edit.
export const docs = [
  {
    "path": ".cursor/rules/readme.md",
    "title": "Rules"
  },
  {
    "path": ".github/readme.md",
    "title": ".github"
  },
  {
    "path": ".github/scripts/readme.md",
    "title": "Scripts"
  },
  {
    "path": ".husky/readme.md",
    "title": ".husky"
  },
  {
    "path": ".vscode/readme.md",
    "title": ".vscode"
  },
  {
    "path": "api/readme.md",
    "title": "API — OpenAPI Specs & Tooling"
  },
  {
    "path": "app/(auth)/readme.md",
    "title": "(auth)"
  },
  {
    "path": "app/(marketing)/readme.md",
    "title": "(marketing)"
  },
  {
    "path": "app/(protected)/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "app/(protected)/readme.md",
    "title": "(protected)"
  },
  {
    "path": "app/api/health/readme.md",
    "title": "Health"
  },
  {
    "path": "app/api/internal/readme.md",
    "title": "Internal"
  },
  {
    "path": "app/api/readme.md",
    "title": "Api"
  },
  {
    "path": "app/api/v1/readme.md",
    "title": "V1"
  },
  {
    "path": "app/readme.md",
    "title": "App"
  },
  {
    "path": "components/auth/readme.md",
    "title": "components/auth"
  },
  {
    "path": "components/billing/readme.md",
    "title": "components/billing"
  },
  {
    "path": "components/chat/readme.md",
    "title": "components/chat"
  },
  {
    "path": "components/dashboard/entities/addresses/readme.md",
    "title": "components/dashboard/entities/addresses"
  },
  {
    "path": "components/dashboard/entities/companies/readme.md",
    "title": "components/dashboard/entities/companies"
  },
  {
    "path": "components/dashboard/entities/projects/readme.md",
    "title": "components/dashboard/entities/projects"
  },
  {
    "path": "components/dashboard/entities/readme.md",
    "title": "components/dashboard/entities"
  },
  {
    "path": "components/dashboard/layout/readme.md",
    "title": "components/dashboard/layout"
  },
  {
    "path": "components/dashboard/readme.md",
    "title": "components/dashboard"
  },
  {
    "path": "components/dashboard/sidebar/readme.md",
    "title": "components/dashboard/sidebar"
  },
  {
    "path": "components/forms/readme.md",
    "title": "components/forms"
  },
  {
    "path": "components/insights/layout/readme.md",
    "title": "components/insights/layout"
  },
  {
    "path": "components/insights/readme.md",
    "title": "components/insights"
  },
  {
    "path": "components/landing/layout/readme.md",
    "title": "README"
  },
  {
    "path": "components/landing/readme.md",
    "title": "components/landing"
  },
  {
    "path": "components/landing/sections/market-insights/readme.md",
    "title": "components/landing/sections/market-insights"
  },
  {
    "path": "components/landing/sections/readme.md",
    "title": "components/landing/sections"
  },
  {
    "path": "components/landing/sections/roi/readme.md",
    "title": "components/landing/sections/roi"
  },
  {
    "path": "components/landing/widgets/readme.md",
    "title": "components/landing/widgets"
  },
  {
    "path": "components/marketing/readme.md",
    "title": "components/marketing"
  },
  {
    "path": "components/marketing/sections/contact/readme.md",
    "title": "README"
  },
  {
    "path": "components/marketing/sections/legal/readme.md",
    "title": "README"
  },
  {
    "path": "components/marketing/sections/pricing/readme.md",
    "title": "components/marketing/sections/pricing"
  },
  {
    "path": "components/marketing/sections/readme.md",
    "title": "components/marketing/sections"
  },
  {
    "path": "components/marketing/widgets/readme.md",
    "title": "components/marketing/widgets"
  },
  {
    "path": "components/readme.md",
    "title": "components"
  },
  {
    "path": "components/ui/atoms/icon/readme.md",
    "title": "components/ui/atoms/icon"
  },
  {
    "path": "components/ui/atoms/readme.md",
    "title": "components/ui/atoms"
  },
  {
    "path": "components/ui/molecules/readme.md",
    "title": "components/ui/molecules"
  },
  {
    "path": "components/ui/organisms/footer-system/readme.md",
    "title": "components/ui/organisms/footer-system"
  },
  {
    "path": "components/ui/organisms/navbar/readme.md",
    "title": "components/ui/organisms/navbar"
  },
  {
    "path": "components/ui/organisms/readme.md",
    "title": "components/ui/organisms"
  },
  {
    "path": "components/ui/patterns/readme.md",
    "title": "components/ui/patterns"
  },
  {
    "path": "components/ui/readme.md",
    "title": "components/ui"
  },
  {
    "path": "components/ui/shared/readme.md",
    "title": "components/ui/shared"
  },
  {
    "path": "config/readme.md",
    "title": "Config"
  },
  {
    "path": "config/typescript/readme.md",
    "title": "Typescript"
  },
  {
    "path": "contexts/readme.md",
    "title": "contexts"
  },
  {
    "path": "docs/decisions/readme.md",
    "title": "docs/decisions"
  },
  {
    "path": "docs/feature-notes/readme.md",
    "title": "docs/feature-notes"
  },
  {
    "path": "docs/qa/readme.md",
    "title": "docs/qa"
  },
  {
    "path": "docs/readme.md",
    "title": "docs"
  },
  {
    "path": "docs/references/readme.md",
    "title": "docs/references"
  },
  {
    "path": "docs/security/readme.md",
    "title": "docs/security"
  },
  {
    "path": "eslint-plugin-corso/readme.md",
    "title": "Eslint Plugin Corso"
  },
  {
    "path": "lib/actions/readme.md",
    "title": "lib/actions"
  },
  {
    "path": "lib/api/readme.md",
    "title": "lib/api"
  },
  {
    "path": "lib/auth/readme.md",
    "title": "lib/auth"
  },
  {
    "path": "lib/chat/readme.md",
    "title": "lib/chat"
  },
  {
    "path": "lib/core/readme.md",
    "title": "lib/core"
  },
  {
    "path": "lib/entities/readme.md",
    "title": "lib/entities"
  },
  {
    "path": "lib/integrations/readme.md",
    "title": "lib/integrations"
  },
  {
    "path": "lib/marketing/readme.md",
    "title": "lib/marketing"
  },
  {
    "path": "lib/middleware/readme.md",
    "title": "lib/middleware"
  },
  {
    "path": "lib/monitoring/readme.md",
    "title": "lib/monitoring"
  },
  {
    "path": "lib/ratelimiting/readme.md",
    "title": "lib/ratelimiting"
  },
  {
    "path": "lib/readme.md",
    "title": "lib"
  },
  {
    "path": "lib/security/readme.md",
    "title": "lib/security"
  },
  {
    "path": "lib/server/readme.md",
    "title": "lib/server"
  },
  {
    "path": "lib/shared/readme.md",
    "title": "Shared"
  },
  {
    "path": "lib/validators/readme.md",
    "title": "lib/validators"
  },
  {
    "path": "public/readme.md",
    "title": "Public"
  },
  {
    "path": "readme.md",
    "title": "."
  },
  {
    "path": "scripts/analysis/readme.md",
    "title": "scripts/analysis"
  },
  {
    "path": "scripts/audit/readme.md",
    "title": "scripts/audit"
  },
  {
    "path": "scripts/ci/readme.md",
    "title": "README"
  },
  {
    "path": "scripts/codemods/readme.md",
    "title": "scripts/codemods"
  },
  {
    "path": "scripts/docs/readme.md",
    "title": "scripts/docs"
  },
  {
    "path": "scripts/lint/readme.md",
    "title": "scripts/lint"
  },
  {
    "path": "scripts/maintenance/docs/readme.md",
    "title": "scripts/maintenance/docs"
  },
  {
    "path": "scripts/maintenance/readme.md",
    "title": "scripts/maintenance"
  },
  {
    "path": "scripts/readme.md",
    "title": "scripts"
  },
  {
    "path": "scripts/rules/ast-grep/readme.md",
    "title": "scripts/rules/ast-grep"
  },
  {
    "path": "scripts/rules/readme.md",
    "title": "README"
  },
  {
    "path": "scripts/setup/readme.md",
    "title": "scripts/setup"
  },
  {
    "path": "scripts/tools/readme.md",
    "title": "scripts/tools"
  },
  {
    "path": "scripts/utils/readme.md",
    "title": "scripts/utils"
  },
  {
    "path": "scripts/validation/readme.md",
    "title": "scripts/validation"
  },
  {
    "path": "styles/readme.md",
    "title": "styles"
  },
  {
    "path": "styles/tokens/readme.md",
    "title": "styles/tokens"
  },
  {
    "path": "styles/ui/atoms/readme.md",
    "title": "styles/ui/atoms"
  },
  {
    "path": "styles/ui/molecules/readme.md",
    "title": "styles/ui/molecules"
  },
  {
    "path": "styles/ui/organisms/readme.md",
    "title": "styles/ui/organisms"
  },
  {
    "path": "styles/ui/patterns/readme.md",
    "title": "styles/ui/patterns"
  },
  {
    "path": "styles/ui/readme.md",
    "title": "styles/ui"
  },
  {
    "path": "styles/ui/shared/readme.md",
    "title": "styles/ui/shared"
  },
  {
    "path": "supabase/readme.md",
    "title": "Supabase"
  },
  {
    "path": "tests/api/readme.md",
    "title": "Api"
  },
  {
    "path": "tests/auth/readme.md",
    "title": "Auth"
  },
  {
    "path": "tests/chat/readme.md",
    "title": "Chat"
  },
  {
    "path": "tests/core/readme.md",
    "title": "Core"
  },
  {
    "path": "tests/dashboard/readme.md",
    "title": "Dashboard"
  },
  {
    "path": "tests/e2e/readme.md",
    "title": "E2e"
  },
  {
    "path": "tests/insights/readme.md",
    "title": "Insights"
  },
  {
    "path": "tests/integrations/readme.md",
    "title": "Integrations"
  },
  {
    "path": "tests/lib/readme.md",
    "title": "Lib"
  },
  {
    "path": "tests/readme.md",
    "title": "Tests"
  },
  {
    "path": "tests/routes/readme.md",
    "title": "Routes"
  },
  {
    "path": "tests/runtime-boundary/readme.md",
    "title": "Runtime Boundary"
  },
  {
    "path": "tests/scripts/readme.md",
    "title": "Scripts"
  },
  {
    "path": "tests/security/readme.md",
    "title": "Security"
  },
  {
    "path": "tests/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "tests/styles/readme.md",
    "title": "README"
  },
  {
    "path": "tests/support/harness/readme.md",
    "title": "Harness"
  },
  {
    "path": "tests/support/readme.md",
    "title": "README"
  },
  {
    "path": "tests/support/setup/readme.md",
    "title": "Setup"
  },
  {
    "path": "tests/types/readme.md",
    "title": "Types"
  },
  {
    "path": "tests/ui/readme.md",
    "title": "Ui"
  },
  {
    "path": "tests/vendors/readme.md",
    "title": "Vendors"
  },
  {
    "path": "types/api/readme.md",
    "title": "README"
  },
  {
    "path": "types/chat/readme.md",
    "title": "types/chat"
  },
  {
    "path": "types/dashboard/readme.md",
    "title": "types/dashboard"
  },
  {
    "path": "types/marketing/readme.md",
    "title": "types/marketing"
  },
  {
    "path": "types/readme.md",
    "title": "types"
  },
  {
    "path": "types/shared/readme.md",
    "title": "Shared"
  },
  {
    "path": "docs/security/dependency-policy.md",
    "title": "Dependency Policy"
  }
] as const;
