create table public.dev_metrics (
  id          bigint generated by default as identity primary key,
  ts          timestamptz default now(),
  metric      text not null,
  job         text not null,
  value_ms    integer not null,
  branch      text not null,
  sha         text not null,
  runner      text not null,
  constraint dev_metrics_org_fkey foreign key (branch) references public.branches(name)
);

alter table public.dev_metrics
  enable row level security;

create policy "ci can insert metrics"
  on public.dev_metrics
  for insert
  with check (auth.role() = 'service_role');

