/**
 * DO NOT EDIT THIS FILE - This is a shim that re-exports the root Tailwind config.
 * 
 * This file exists only to satisfy test dependencies (tests/styles/breakpoints.spec.ts).
 * All Tailwind configuration should be done in the root tailwind.config.ts file.
 * 
 * If you need to modify Tailwind configuration, edit: tailwind.config.ts (root)
 */
import config from '../tailwind.config';

export default config;
